{% set name = "pysyncrosim" %}
{% set version = "2.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pysyncrosim-{{ version }}.tar.gz
  sha256: 83f656f342d5301f6d4b78d88b283477bb896a7a9b02afdb7f840a393d94771d

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - pandas
    - numpy
    - rasterio
  run:
    - python >={{ python_min }}
    - pandas
    - numpy
    - rasterio

test:
  imports:
    - pysyncrosim
    - tests
  commands:
    - pip check
  requires:
    - pip
    - pytest
    - python {{ python_min }}

about:
  home: https://syncrosim.com/
  summary: Python interface to SyncroSim
  license: MIT
  license_file: LICENSE
  doc_url: https://pysyncrosim.readthedocs.io/en/latest/
  dev_url: https://github.com/syncrosim/pysyncrosim/

extra:
  recipe-maintainers:
    - katieb1
